In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

# Load dataset
df = pd.read_csv("../data/raw/retail_store_inventory.csv")

# Convert Date to datetime
df["Date"] = pd.to_datetime(df["Date"])

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

Dataset loaded successfully!
Rows: 73100
Columns: 15

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,20,Sunny,0,66.16,Autumn
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,10,Sunny,1,31.32,Summer
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,10,Cloudy,1,34.74,Autumn
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,0,Sunny,0,68.95,Summer

In [3]:
print("Dataset shape:", df.shape)

print("\nMissing values per column:")
print(df.isnull().sum())

print("\nTotal missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

Dataset shape: (73100, 15)

Missing values per column:
Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Demand Forecast       0
Price                 0
Discount              0
Weather Condition     0
Holiday/Promotion     0
Competitor Pricing    0
Seasonality           0
dtype: int64

Total missing values: 0
Duplicate rows: 0

In [4]:
df.info()

print("\nDate range:")
print(df["Date"].min(), "to", df["Date"].max())

print("\nUnique stores:", df["Store ID"].nunique())
print("Unique products:", df["Product ID"].nunique())

print("\nSales summary:")
print(df["Units Sold"].describe())

<class 'pandas.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  datetime64[us]
 1   Store ID            73100 non-null  str
 2   Product ID          73100 non-null  str
 3   Category            73100 non-null  str
 4   Region              73100 non-null  str
 5   Inventory Level     73100 non-null  int64
 6   Units Sold          73100 non-null  int64
 7   Units Ordered       73100 non-null  int64
 8   Demand Forecast     73100 non-null  float64
 9   Price               73100 non-null  float64
 10  Discount            73100 non-null  int64
 11  Weather Condition   73100 non-null  str
 12  Holiday/Promotion   73100 non-null  int64
 13  Competitor Pricing  73100 non-null  float64
 14  Seasonality         73100 non-null  str
dtypes: datetime64[us](1), float64(3), int64(5), str(6)
memory usage: 10.7 MB

Date range:
2022-01-01 00:00:00 to 2024-01-01 00:00:00

Unique stores: 5
Unique products: 20

Sales summary:
count    73100.000000
mean       136.464870
std        108.919406
min          0.000000
25%         49.000000
50%        107.000000
75%        203.000000
max        499.000000
Name: Units Sold, dtype: float64

In [5]:
daily_sales = (
    df.groupby("Date", as_index=False)["Units Sold"]
      .sum()
)

fig = px.line(
    daily_sales,
    x="Date",
    y="Units Sold",
    title="Daily Total Units Sold",
    labels={
        "Date": "Date",
        "Units Sold": "Total Units Sold"
    }
)

fig.show()

In [9]:
df.info()

print("\nDate range:")
print(df["Date"].min(), "to", df["Date"].max())

print("\nUnique stores:", df["Store ID"].nunique())
print("Unique products:", df["Product ID"].nunique())

print("\nSales statistics:")
print(df["Units Sold"].describe())

<class 'pandas.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  datetime64[us]
 1   Store ID            73100 non-null  str
 2   Product ID          73100 non-null  str
 3   Category            73100 non-null  str
 4   Region              73100 non-null  str
 5   Inventory Level     73100 non-null  int64
 6   Units Sold          73100 non-null  int64
 7   Units Ordered       73100 non-null  int64
 8   Demand Forecast     73100 non-null  float64
 9   Price               73100 non-null  float64
 10  Discount            73100 non-null  int64
 11  Weather Condition   73100 non-null  str
 12  Holiday/Promotion   73100 non-null  int64
 13  Competitor Pricing  73100 non-null  float64
 14  Seasonality         73100 non-null  str
dtypes: datetime64[us](1), float64(3), int64(5), str(6)
memory usage: 10.7 MB

Date range:
2022-01-01 00:00:00 to 2024-01-01 00:00:00

Unique stores: 5
Unique products: 20

Sales statistics:
count    73100.000000
mean       136.464870
std        108.919406
min          0.000000
25%         49.000000
50%        107.000000
75%        203.000000
max        499.000000
Name: Units Sold, dtype: float64

In [10]:
category_sales = (
    df.groupby("Category", as_index=False)["Units Sold"]
      .sum()
      .sort_values("Units Sold", ascending=False)
)

category_sales

      Category  Units Sold
2    Furniture     2025017
3    Groceries     2000482
0     Clothing     1999166
4         Toys     1990485
1  Electronics     1960432

In [11]:
fig = px.bar(
    category_sales,
    x="Category",
    y="Units Sold",
    title="Total Units Sold by Product Category",
    labels={"Units Sold": "Total Units Sold"},
    text="Units Sold"
)

fig.show()

In [12]:
region_sales = (
    df.groupby("Region", as_index=False)["Units Sold"]
      .sum()
      .sort_values("Units Sold", ascending=False)
)

region_sales

  Region  Units Sold
0   East     2511265
2  South     2507799
1  North     2484966
3   West     2471552

In [13]:
fig = px.bar(
    region_sales,
    x="Region",
    y="Units Sold",
    title="Total Units Sold by Region",
    text="Units Sold"
)

fig.show()

In [14]:
inventory_summary = (
    df.groupby("Category", as_index=False)
      .agg(
          Average_Inventory=("Inventory Level", "mean"),
          Average_Daily_Sales=("Units Sold", "mean"),
          Total_Units_Ordered=("Units Ordered", "sum")
      )
      .round(2)
)

inventory_summary

      Category  Average_Inventory  Average_Daily_Sales  Total_Units_Ordered
0     Clothing             274.60               136.69              1614885
1  Electronics             272.51               135.01              1592333
2    Furniture             275.82               137.77              1617699
3    Groceries             275.76               136.92              1606188
4         Toys             273.65               135.93              1610222

In [15]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

actual = df["Units Sold"]
forecast = df["Demand Forecast"]

mae = mean_absolute_error(actual, forecast)
rmse = np.sqrt(mean_squared_error(actual, forecast))

print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")

MAE: 8.34
RMSE: 10.02

In [16]:
# Count and inspect negative demand forecasts
negative_forecasts = df[df["Demand Forecast"] < 0]

print("Negative forecast rows:", len(negative_forecasts))
print("Percentage of dataset:", round(len(negative_forecasts) / len(df) * 100, 2), "%")

negative_forecasts[
    ["Date", "Store ID", "Product ID", "Category",
     "Units Sold", "Demand Forecast"]
].head(15)

Negative forecast rows: 673
Percentage of dataset: 0.92 %

           Date Store ID Product ID     Category  Units Sold  Demand Forecast
63   2022-01-01     S004      P0004    Groceries           0            -2.40
141  2022-01-02     S003      P0002    Groceries           2            -3.40
278  2022-01-03     S004      P0019         Toys           1            -3.91
511  2022-01-06     S001      P0012    Groceries           1            -8.37
730  2022-01-08     S002      P0011  Electronics           7            -2.99
844  2022-01-09     S003      P0005    Furniture           4            -1.33
1011 2022-01-11     S001      P0012         Toys           3            -6.05
1107 2022-01-12     S001      P0008     Clothing           0            -3.55
1149 2022-01-12     S003      P0010    Furniture           6            -0.11
1180 2022-01-12     S005      P0001         Toys           6            -2.04
1240 2022-01-13     S003      P0001    Groceries           2            -7.96
1398 2022-01-14     S005      P0019    Groceries           0            -0.03
1412 2022-01-15     S001      P0013    Groceries           4            -4.70
1416 2022-01-15     S001      P0017         Toys           8            -0.85
1859 2022-01-19     S003      P0020    Furniture           5            -3.55

In [17]:
negative_forecasts.groupby("Category").agg(
    Negative_Forecast_Rows=("Demand Forecast", "size"),
    Average_Forecast=("Demand Forecast", "mean"),
    Minimum_Forecast=("Demand Forecast", "min")
).sort_values("Negative_Forecast_Rows", ascending=False)

             Negative_Forecast_Rows  Average_Forecast  Minimum_Forecast
Category
Groceries                       143         -3.655944             -9.99
Toys                            140         -3.734071             -9.58
Clothing                        132         -3.510530             -9.79
Furniture                       129         -3.701938             -9.67
Electronics                     129         -3.871085             -9.97

In [18]:
numeric_columns = [
    "Inventory Level",
    "Units Sold",
    "Units Ordered",
    "Demand Forecast",
    "Price",
    "Discount",
    "Competitor Pricing"
]

for col in numeric_columns:
    values = pd.to_numeric(df[col], errors="coerce")
    print(f"{col}: {(values < 0).sum()} negative values")

Inventory Level: 0 negative values
Units Sold: 0 negative values
Units Ordered: 0 negative values
Demand Forecast: 673 negative values
Price: 0 negative values
Discount: 0 negative values
Competitor Pricing: 0 negative values